version: 2

jobs:
  node_modules:
    docker:
      - image: circleci/node:13.4.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile

      - run:
          command: yarn autoclean --force

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build:
    docker:
      - image: circleci/node:13.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          command: yarn install --frozen-lockfile

      - run:
          command: yarn workspace skapa-web run now-build

      - persist_to_workspace:
          root: .
          paths:
            - web/.next

  packtrack:
    docker:
      - image: circleci/node:13.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile

      - attach_workspace:
          at: .

      - run:
          command: yarn workspace skapa-web run packtracker-upload --stats=.next/stats.json

workflows:
  version: 2
  feature:
    jobs:
      - node_modules
      - build:
          requires:
            - node_modules
      - packtrack:
          requires:
            - build
