aliases:
  - &restore-cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}
  - &yarn-install
    name: 'Yarn install'
    command: yarn install --ignore-engines
  - &save-cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

master_only: &master_only
  filters:
    branches:
      only: master

master_ignore: &master_ignore
  filters:
    branches:
      ignore: master

defaults: &defaults
  docker:
    - image: circleci/node:13.4.0

version: 2

jobs:
  node_modules:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - save_cache: *save-cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - run:
          name: Build Skapa Web
          command: yarn workspace skapa-web run build
      - persist_to_workspace:
          root: .
          paths:
            - web/.next

  unit_and_integration:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - run:
          name: Unit and Integration tests
          command: yarn test

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - run:
          name: Run Eslint
          command: yarn lint
  flow:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - run:
          name: Run flow
          command: yarn flow check

  stage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  packtrack:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn-install
      - attach_workspace:
          at: .
      - run:
          name: Upload webpack stats to packtracker
          command: yarn workspace skapa-web run packtracker-upload --stats=.next/stats.json

workflows:
  version: 2
  feature:
    jobs:
      - node_modules:
          <<: *master_ignore
      - unit_and_integration:
          <<: *master_ignore
          requires:
            - node_modules
      - lint:
          <<: *master_ignore
          requires:
            - node_modules
      - flow:
          <<: *master_ignore
          requires:
            - node_modules
      - build:
          <<: *master_ignore
          requires:
            - unit_and_integration
            - lint
            - flow
      - packtrack:
          <<: *master_ignore
          requires:
            - build
  master:
    jobs:
      - node_modules:
          <<: *master_only
      - unit_and_integration:
          <<: *master_only
          requires:
            - node_modules
      - lint:
          <<: *master_only
          requires:
            - node_modules
      - flow:
          <<: *master_only
          requires:
            - node_modules
      - build:
          <<: *master_only
          requires:
            - unit_and_integration
            - lint
            - flow
      - packtrack:
          <<: *master_only
          requires:
            - build
      - stage:
          <<: *master_only
          requires:
            - packtrack
