name: Feature

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: branch
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup
        run: |
          yarn
      - name: Lint & Test
        run: |
          yarn lint
          yarn test
      - name: Setup git
        run: |
          git config --global user.email "skapa@bot.com"
          git config --global user.name "skapa-bot"
          git remote set-url origin https://christoferolaison:${GITHUB_TOKEN}@github.com/christoferolaison/skapa.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup npm
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish packages
        run: |
          npx skapa publish --next
      - name: Deploy
        run: |
          npx skapa deploy --feature
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
