name: Master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup 
        run: |
          yarn
      - name: Lint & Test 
        run: |
          yarn lint
          yarn test
      - name: Build packages 
        run: |
          npx skapa build
      - name: Setup git
        run: | 
          git config --global user.email "skapa@bot.com"
          git config --global user.name "skapa-bot"
          git remote set-url origin https://christoferolaison:${GITHUB_TOKEN}@github.com/christoferolaison/skapa.git
          git checkout master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish packages 
        run: |
          npx skapa publish
        
